#include<stdio.h>
#include<string.h>
int story();
int ending();
void main()
{
    
    char ch6,ch7,ch8;
    int lvl;
    printf("            LEVEL 2 !!!!!!!!!!!!!            ");
    printf("\nWELCOME TO THE ADVENTURES OF DUNGEON RUN.\nCONGRATULATIONS.\n\t\t\tLETS BEGIN !!!!!! ");
    printf("\nARE YOU READY FOR THE ADVENTURE! ONCE ENTERED THERE IS NO TURNING BACK!!! y/n ??????");
    scanf(" %c",&ch6);
    if(ch6=='y'||ch6=='Y')
    {
        printf("HI Mr.MAGNUS LORD.\nYOU JOINED THE ADVENTURERS AND MOVED ON.\nTHEY ARE A BUNCH OF KIND-HEARTED PEOPLE.\nTHERE ARE 4 OF THEM.\nYOU JOINED THEM AND THEY STARTED TO MAKE TINY CONVERSATIONS.\nBUT YOU STAYED QUIET.\nTHE SILENCE OF THE NIGHT IS KILLING YOU,\nMAKING YOU REMEMBER ALL THE MOMENTS EITH YOUR PARENTS.\nIT IS SILENTLY SUCKING YOUR SOUL OUT.\nYOUR MIND WAS BLANK BECAUSE OF THE THOUGHTS\n AND YOU WERE UNABLE TO LISTEN TO ANYTHING THAT SURROUNDS YOU.\nTHE DINNERS THAT YOU HAD,THE LAUGHTER THAT YOU SHARED,\nEACH AND EVERY MOMENT OF YOUR LIFE IS KILLING YOU FROM INSIDE.\nHEY!!!! SUDDENLY CALLED ONE OF THE ADVENTURERS.....\nYOU  CAME BACK TO THE PRESENT WORLD,\nYOU ARE AT THE EDGE OF BURSTING OUT INTO TEARS ,\nBUT ANGER FILLED INSIDE YOU.\nYOUR EMOTIONS WERE ALL OVER THE PLACE.\nYOU CONTROLLED ALL THE EMOTIONS AND FORCED A SMALL SMILE ON YOUR FACE\nNOW YOU STARTED TALKING WITH THEM .\nTALKING AND WALKING IN THE EERILY SILENT DUNGEON.\nYOU CAN'T HEAR NOTHING BUT YOUR CONVERSATIONS.\nSUDDENLY YOU HEARD A SOUND.\nYOU TURNED BACK AND YOU SAW NOTHING.\nALL THE PEOPLE WHO YOU WERE TALKING WITH VANISHED .....\nTHE ADVENTURERS ARE NO WHERE TO BE SEEM\nAMIDST OF THE HORRYIFYING DARKNESS AND SILENCE YOU ARE ALL ALONE..... ");
        printf("YOU ARE CONFUSED WITH ALL THE EMOTIONS.\nTERRIFIED ,DEPRESSED AND ANGRY.\nYOU LOST EVERY PEACE OF YOUR MIND.\nYOU STILL HAVE YOUR SWORD......\nBUT YOU ARE TIRED.YOU ARE THIRSTY AND HUNGRY.\nTHERE IS A CORRIDOR IN THE DUNGEON THAT PASS YOU TO A MAGICAL ROOM\nTHERE YOU CAN FIND A TREE IN THE MIDDLE OF THE LAKE .\nA MAGICIAN IS LIVING IN THE TREE. \nHE HAS A GINN AS HIS SERVENT AND HE COULD GIVE YOU ANYTHING YOU WANT. \nIF YOU WANT TO SURVIVE YOU HAVE TO REACH THERE.\nBUT REACHING THERE IS SO HARD. \nON YOUR PATH YOU WILL HAVE TO FACE MANY DANGERS ,\nMOREOVER YOU HAVE TO SURVIVE THE GREAT MONSTER OF MOORS.\nTHE MONSTER CAN KILL YOU WITH JUST LOOKING INTO YOUR EYES,\nIT IS AN ALL POWERFUL MONSTER THAT HAS THE POWER OF 10 TIGERS TOGETHER .\nWILL YOU STILL ACCEPT THE RISK AND MOVE FORWARD???");
        scanf(" %c",&ch7);
        if(ch7=='y'||ch7=='Y')
        {
            printf("\nYOU STILL CHOOSE TO CONTINUE.YOU ARE BRAVE .\nYOU SURVIVED THE MONSTER AND YOU REACHED THE LAKE AND YOU ARE NOW READY TO CONTINUE...\nYOU GOT A MIND MAP FROM THE GINN AND YOU STARTED WALKING ACCORDING TO IT..\nYOU ARE PLANNING TO KILL IT BY MIDNIGHT.\nON YOUR WAY YOU FIND A SECRET WEAPON ,\nA DRAGON SWORD WITH A GEM IN ITS CENTRE THAT CAN SPIT FIRE.....\nYOU CAN KILL ANY MONSTER WITH IT.\nBUT IN ORDER TO GET IT YOU HAVE TO CROSS THE HEART OF THE DRAGON \nWHERE THE GREAT WIZARD LIVES.\nHE IS VERY TRICKY AND CAN LEAD YOU TO DESTRUCTION....\nWILL YOU ACCEPT THE RISK AND GET THE SWORD???");
            scanf(" %c",&ch8);
            if(ch8=='y'||ch8=='Y')
            {
                story();
                
                lvl=3;
            }
            else
            {
                printf("\nIT WAS AN UNWISE DECISION..... ANYWAYS YOU HAVE THE OTHER SWORD..... BUT BE CAREFULL ..... ");
                story();
                lvl=3;
            }
        }
        else
        {
            ending();
        }
    }
    else
    {
        ending();
    }
}
int story()
{ 
    char cch3;
    printf("IT WAS A WISE DECISION. NOW YOU ARE POWERFUL ENOUGH TO KILL THE MONSTER . \nYOU WILL REACH ITS DEN BY MIDNIGHT.\nYOU CONTINUE TO WALK AND YOU REACHED THE DEN. YOU CAN SEE THE BEAST. \nBUT YOU NOTICED SOMETHING ELSE. YOU NOTICED ONE OF THE ADVENTURERS AND ONE OF THEM TRANSFORMING INTO THE BEAST .\nYOU STAYED SILENT AND WATCHED EVERYTHING,SUDDENLY YOU NOTICED SOMETHING ELSE.... \n                        ITS YOUR FAMILY.....                  \nYOU GET SHOCKED. YOU WERE MENTALLY UNPREPARED TO SEE YOUR PARENTS LIKE THAT.\nYOU THOUGHT THAT THE BEASTS WERE SOME MAGICAL BEINGS AND WAS TRYING TO CAPTURE YOUR FAMILY.... \nIN ALL EXICETMENT AND HAPPINESS TO SEE YOUR FAMILY BACK YOU RAN INTO THEM .\nONE OF THE BEAST ATTACKED YOU.BUT WITH ALL YOUR STRENGTH YOU FOUGHT BACK.\nYOU TRIED TO USE THE DRAGON SWORD. YOU TOOK IT AND ACTIVATED THE GEM.\nBUT.. SUDDENLY YOUR MOTHER TRANSFORMED INTO A BEAST AND STOPPED YOU... SHE STOPPED THE OTHER BEAST ALSO.\nEVERYONE,HUMANS AND THE BEASTS STAYED SILENT .YOU WERE BEGINING TO FALL. THE FIGHT BROUGHT OUT ALL OF THE STRENGTH IN YOU.YOU FELL DOWN.\nBY THE MORNING THE PACK HAS LEFT THE LAYER 2 .YOUR WOUNDS WERE ALL TREATED. YOU WERE HEALTHY AND FRESH AS A NEW-BORN.\nNOW, AT THE MOMENT YOU HAVE THE PEACE THAT BY SEEING YOUR FAMILY AND YOU HAVE THE HOPE THAT YOU CAN SEE THEM AGAIN. ");
printf("\nBUT YOU STILL HAVE MANY QUESTIONS?? YOU WANTS TO KNOW THE UNREAD CHAPTER OF YOUR AND YOURS FAMILY... YOU WANTS TO KNOW EVERYTHING..\nAND YOU WANT THE OLD FAMILY BACK..THE INNOCENT,HAPPY,SMALL FAMILY BACK... \nARE YOU READY TO CONTINUE TO LAYER 3??");
scanf(" %c",&cch3);

return 0;
}
int ending()
{
    printf("\nMAGNUS FAILED THE TASK AND RAN AWAY IN FEAR");
    return 0;
}
